apiVersion: v1
kind: Service
metadata:
  name: restaurants-microservice-service
spec:
  selector:
    app: restaurants-microservice
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer