# Generated by Django 5.0.4 on 2024-05-31 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estiloComida', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Comida',
            },
        ),
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'Precio',
            },
        ),
        migrations.CreateModel(
            name='TipoComida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreComida', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'TipoComida',
            },
        ),
        migrations.CreateModel(
            name='Tipoestablecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreEstablecimiento', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'TipoEstablecimiento',
            },
        ),
        migrations.CreateModel(
            name='Restaurante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default=None, max_length=50)),
                ('pais', models.CharField(default=None, max_length=50)),
                ('ciudad', models.CharField(default=None, max_length=50)),
                ('direccion', models.CharField(default=None, max_length=80)),
                ('estiiloComida', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='estiloComida_Comida', to='Explora.comida')),
                ('precio', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='precio_Precio', to='Explora.precio')),
                ('nombreComida', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='nombreComida_TipoComida', to='Explora.tipocomida')),
                ('nombreEstablecimiento', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='nombreEstablecimiento_TipoEstablecimiento', to='Explora.tipoestablecimiento')),
            ],
            options={
                'db_table': 'Restaurante',
            },
        ),
    ]
