# Generated by Django 5.0.4 on 2024-06-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Explora', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurante',
            old_name='estiiloComida',
            new_name='estiloComida',
        ),
    ]
